import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import { writeFileSync } from 'fs';
import { renderHead } from './src/seo/head';
import { PAGE_SEO } from './src/seo/pages';

// Writes the home page's SEO tags into index.html so they are in the HTML
// before any JavaScript runs. On build it also saves the final HTML as
// api/_template.js, which api/page.ts serves for every other route.
const seoHead = (): Plugin => ({
  name: 'seo-head',
  transformIndexHtml: (html) =>
    html.replace('<!--seo-head-->', renderHead(PAGE_SEO.home)),
  writeBundle: (_, bundle) => {
    const indexHtml = bundle['index.html'];
    if (indexHtml?.type !== 'asset') return;

    writeFileSync(
      path.resolve(__dirname, 'api/_template.js'),
      `// Generated by vite.config.ts on build. Do not edit.\nexport default ${JSON.stringify(String(indexHtml.source))};\n`,
    );
  },
});

// https://vite.dev/config/
export default defineConfig({
  plugins: [react(), seoHead()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
      '@api': path.resolve(__dirname, 'src/api'),
      '@app': path.resolve(__dirname, 'src/app'),
      '@assets': path.resolve(__dirname, 'src/assets'),
      '@components': path.resolve(__dirname, 'src/components'),
      '@hooks': path.resolve(__dirname, 'src/hooks'),
      '@layout': path.resolve(__dirname, 'src/layout'),
      '@pages': path.resolve(__dirname, 'src/pages'),
      '@types': path.resolve(__dirname, 'src/types'),
      '@utils': path.resolve(__dirname, 'src/utils'),
      '@features': path.resolve(__dirname, 'src/features'),
      '@guards': path.resolve(__dirname, 'src/guards'),
    },
  },
});
