export const SIDEBAR_ITEMS = [
  { id: 1, text: 'Faqja Kryesore', path: '/' },
  { id: 2, text: 'Shto Prone', path: '/admin-addProperty' },
  { id: 3, text: 'Pronat', path: '/admin-manageProperty' },
  { id: 4, text: 'Shto Bileta', path: '/planeTickets' },
  { id: 5, text: 'Shto Paketa Turistike', path: '/packages' },
  { id: 6, text: 'Shto Hotel', path: '/hotel' },
  { id: 7, text: 'Shto Destinacion', path: '/destinations' },
];

export const HeaderItems = [
  { id: 1, name: 'home', path: '/' },
  { id: 2, name: 'property', path: '/property' },
  { id: 3, name: 'packages', path: '/packages' },
  { id: 4, name: 'plane tickets', path: '/planeTickets' },
  { id: 5, name: 'hotel', path: '/hotel' },
  { id: 6, name: 'destinations', path: '/destinations' },
  { id: 7, name: 'contact', path: '/contact' },
];

export const LANGUAGES = [
  { id: 1, value: 'en' },
  { id: 2, value: 'it' },
  { id: 3, value: 'de' },
  { id: 4, value: 'esp' },
  { id: 5, value: 'alb' },
];

export const CURRENCIES = [
  { id: 1, value: 'eur' },
  { id: 2, value: 'usd' },
  { id: 3, value: 'all' },
  { id: 4, value: 'chf' },
  { id: 5, value: 'gbp' },
];

export const POPULAR_DESTINATIONS = [
  { id: 1, image: '/places/bora-bora.webp', place: 'bora-bora', country: '' },
  { id: 2, image: '/places/colosseum.avif', place: 'colosseum', country: '' },
  { id: 3, image: '/places/eiffel.jpg', place: 'eiffel tower', country: '' },
  {
    id: 4,
    image: '/places/grand-canyon.avif',
    place: 'grand-canyon',
    country: '',
  },
  { id: 5, image: '/places/great-wall.jpg', place: 'great wall', country: '' },
  { id: 6, image: '/places/himalayas.jpg', place: 'himalayas', country: '' },
  { id: 7, image: '/places/japan.jpg', place: 'japan', country: '' },
  { id: 8, image: '/places/maldives.jpg', place: 'maldives', country: '' },
  {
    id: 9,
    image: '/places/opera-house.jpg',
    place: 'opera-house',
    country: '',
  },
  {
    id: 10,
    image: '/places/statue-of-liberty.avif',
    place: 'statue-of-liberty',
    country: '',
  },
  { id: 11, image: '/places/taj-mahal.webp', place: 'taj-mahal', country: '' },
];

export const FAVORITE_DESTINATIONS = [
  {
    id: 1,
    image: '/favorite/amsterdam.webp',
    city: 'Amsterdam',
    country: 'Netherlands',
    tagline: 'Canals, culture, and carefree charm',
    tours: '57',
    activities: '11',
  },
  {
    id: 2,
    image: '/favorite/budapest.webp',
    city: 'Budapest',
    country: 'Hungary',
    tagline: 'Where history relaxes in thermal waters',
    tours: '36',
    activities: '73',
  },
  {
    id: 3,
    image: '/favorite/lisbon.jpg',
    city: 'Lisbon',
    country: 'Portugal',
    tagline: 'Sunlit hills and soulful streets',
    tours: '14',
    activities: '13',
  },
  {
    id: 4,
    image: '/favorite/london.webp',
    city: 'London',
    country: 'England',
    tagline: 'Timeless tradition meets modern energy',
    tours: '12',
    activities: '54',
  },
  {
    id: 5,
    image: '/favorite/ottawa.jpg',
    city: 'Ottawa',
    country: 'Canada',
    tagline: 'Canada’s capital of culture and nature',
    tours: '24',
    activities: '23',
  },
  {
    id: 6,
    image: '/favorite/paris.avif',
    city: 'Paris',
    country: 'France',
    tagline: 'The city of love and lights',
    tours: '65',
    activities: '53',
  },
  {
    id: 7,
    image: '/favorite/puerto-rico.webp',
    city: 'Puerto Rico',
    country: 'USA',
    tagline: 'Island rhythms and endless sunshine',
    tours: '44',
    activities: '25',
  },
  {
    id: 8,
    image: '/favorite/venice.webp',
    city: 'Venice',
    country: 'Italy',
    tagline: 'A floating masterpiece of romance',
    tours: '52',
    activities: '19',
  },
  {
    id: 9,
    image: '/favorite/tokyo.webp',
    city: 'Tokyo',
    country: 'Japan',
    tagline: 'Tradition meets the future',
    tours: '14',
    activities: '29',
  },
  {
    id: 10,
    image: '/favorite/bali.jpeg',
    city: 'Bali',
    country: 'Indonesia',
    tagline: 'Tropical paradise & culture',
    tours: '16',
    activities: '27',
  },
  {
    id: 11,
    image: '/favorite/dubai.jpeg',
    city: 'Dubai',
    country: 'UAE',
    tagline: 'Luxury beyond imagination',
    tours: '23',
    activities: '34',
  },
  {
    id: 12,
    image: '/favorite/cairo.jpg',
    city: 'Cairo',
    country: 'Egypt',
    tagline: 'Ancient wonders and vibrant bazaars',
    tours: '31',
    activities: '22',
  },
];

export const RECOMMANDIONS = [
  {
    id: 1,
    image: '/packages/stella-di-mare.webp',
    title: 'Stella Di Mare Beach Hotel & Spa + Flight',
    hotelStars: '5 stars - 9.2/10 Wonderful',
    place: 'Sharm El Sheikh',
    stay: '6 nights',
    price: '655$',
  },
  {
    id: 2,
    image: '/packages/jaz-belvedere.jpg',
    title: 'Jaz Belvedere Resort-All Inclusive + Flight',
    hotelStars: '5 stars - 8.6/10 Excellent',
    place: 'Sharm El Sheikh',
    stay: '6 nights',
    price: '819$',
  },
  {
    id: 3,
    image: '/packages/romance.avif',
    title: 'Romance Regency Club Adult Only',
    hotelStars: '4.5 stars - 8/10 Very Good',
    place: 'Sharm El Sheikh',
    stay: '6 nights',
    price: '650$',
  },
  {
    id: 4,
    image: '/packages/xperience-kiroseiz.avif',
    title: 'Romance Regency Club Adult Only',
    hotelStars: '3.5 stars - 7.8/10 Good',
    place: 'Sharm El Sheikh',
    stay: '6 nights',
    price: '575$',
  },
  {
    id: 5,
    image: '/packages/jaz-mirabel.webp',
    title: 'Jaz Mirabel Resort-All Inclusive + Flight',
    hotelStars: '5 stars - 8.6/10 Excellent',
    place: 'Sharm El Sheikh',
    stay: '6 nights',
    price: '819$',
  },
  {
    id: 6,
    image: '/packages/regency-plaza.avif',
    title: 'Regency Plaza Aqua Park & SPA + Flight',
    hotelStars: '4 stars - 8.4/10 Very Good',
    place: 'Sharm El Sheikh',
    stay: '6 nights',
    price: '630$',
  },
  {
    id: 7,
    image: '/packages/serenity.jpg',
    title: 'Serenity Fun City Resort & Spa + Flight',
    hotelStars: '4 stars - 8.2/10 Very Good',
    place: 'Sharm El Sheikh',
    stay: '6 nights',
    price: '720$',
  },
  {
    id: 8,
    image: '/packages/california.jpg',
    title: 'Hotel California & Spa + Flight',
    hotelStars: '4 stars - 8.2/10 Very Good',
    place: 'Sharm El Sheikh',
    stay: '6 nights',
    price: '810$',
  },
  {
    id: 9,
    image: '/packages/rehana.avif',
    title: 'Rehana Royal Beach Resort-Aquapark & SPA',
    hotelStars: '5 stars - 8.6/10 Excellent',
    place: 'Sharm El Sheikh',
    stay: '6 nights',
    price: '732$',
  },
];

export const FLIGHT_OFFERS = [
  {
    id: 1,
    image: '/flights/milano.jpg',
    from: 'tirana',
    to: 'milano',
    price: '25',
    departureAirport: 'tia',
    arrivalAirport: 'mxp',
  },
  {
    id: 2,
    image: '/flights/munich.webp',
    from: 'tirana',
    to: 'munich',
    price: '59',
    departureAirport: 'tia',
    arrivalAirport: 'fmm',
  },
  {
    id: 3,
    image: '/flights/rome.jpg',
    from: 'tirana',
    to: 'rome',
    price: '29',
    departureAirport: 'tia',
    arrivalAirport: 'fco',
  },
  {
    id: 4,
    image: '/flights/vienna.webp',
    from: 'tirana',
    to: 'vienna',
    price: '79',
    departureAirport: 'tia',
    arrivalAirport: 'vie',
  },
  {
    id: 5,
    image: '/flights/istambul.webp',
    from: 'tirana',
    to: 'istanbul',
    price: '89',
    departureAirport: 'tia',
    arrivalAirport: 'ist',
  },
  {
    id: 6,
    image: '/flights/london.webp',
    from: 'tirana',
    to: 'london',
    price: '129',
    departureAirport: 'tia',
    arrivalAirport: 'lhr',
  },
  {
    id: 7,
    image: '/flights/paris.avif',
    from: 'tirana',
    to: 'paris',
    price: '45',
    departureAirport: 'tia',
    arrivalAirport: 'cdg',
  },
  {
    id: 8,
    image: '/flights/dubai.jpeg',
    from: 'tirana',
    to: 'dubai',
    price: '399',
    departureAirport: 'tia',
    arrivalAirport: 'dxb',
  },
  {
    id: 9,
    image: '/flights/barcelona.avif',
    from: 'tirana',
    to: 'barcelona',
    price: '45',
    departureAirport: 'tia',
    arrivalAirport: 'bcn',
  },
  {
    id: 10,
    image: '/flights/athens.jpg',
    from: 'tirana',
    to: 'athens',
    price: '39',
    departureAirport: 'tia',
    arrivalAirport: 'ath',
  },
];

export const FAQ_INFO = [
  {
    id: 1,
    question: 'What travel services do you offer?',
    answer:
      'We offer a complete range of travel services including airline ticket bookings (domestic and international), travel packages, hotel reservations, visa assistance, and travel insurance.',
  },
  {
    id: 2,
    question:
      'Can you help me book flight tickets at the best available price?',
    answer:
      'Yes, we assist with booking flight tickets across multiple airlines and routes. Prices depend on availability, travel dates, and airline rules, and we aim to find the most suitable option for your needs.',
  },
  {
    id: 3,
    question: 'Do you offer holiday and tour packages?',
    answer:
      'Yes, we provide a variety of tour and holiday packages such as family trips, honeymoons, group tours, and customized travel plans based on your preferences.',
  },
  {
    id: 4,
    question: 'Can I change or cancel my flight or travel booking?',
    answer:
      'Changes and cancellations depend on airline and supplier policies. Some bookings are refundable or changeable with fees, while others are non-refundable. We clearly explain all terms before confirmation',
  },
  {
    id: 5,
    question: 'Do you assist with visas and travel documentation?',
    answer:
      'Yes, we provide guidance and assistance with visa applications, required travel documents, and related procedures, depending on the destination.',
  },
  {
    id: 6,
    question: 'Do you provide travel insurance and other add-on services?',
    answer:
      'Yes, we offer travel insurance as well as additional services such as seat selection, extra baggage, special meals, and special assistance requests, subject to airline and provider policies.',
  },
  {
    id: 7,
    question: 'How can I book your travel services?',
    answer:
      'You can book through our office or by phone. Payment options vary and may include bank transfer or cash, depending on the service booked.',
  },
];
